dist: trusty
sudo: true

install:
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5-Linux-x86_64.sh
  - sudo mv cmake-3.*.sh /opt
  - chmod +x /opt/cmake-3.*.sh
  - sudo bash /opt/cmake-3.*.sh --skip-license
  - sudo ln -s /opt/cmake-3.*your_version*/bin/* /usr/local/bin
  - travis_retry wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
  - unzip sonar-scanner-cli-3.3.0.1492-linux.zip
  - export PATH="$PATH:sonar-scanner-cli-3.3.0.1492-linux/bin"

script:
  - mkdir travis
  - cd travis
  - cmake ..
  - travis_retry wget https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
  - unzip build-wrapper-linux-x86.zip
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all

cache:
  directories:
    - '$HOME/.sonar/cache'